config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'movies#index'

  resources :movies, only: [:index, :show]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/movie.rb
class Movie < ApplicationRecord
  mount_uploader :movie_image, ImageUploader
  mount_uploader :movie_url, VideoUploader

  validates :title, presence: true
  validates :movie_url, presence: true
  validates :movie_image, presence: true
  validates :summary, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/models/user_movie.rb
class UserMovie < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name] )
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def show
    
  end
end

app/controllers/movies_controller.rb
require "movie.rb"

class MoviesController < ApplicationController
  before_action :redirect_to_signin

  def index
    @movies = Movie.order('RAND()').limit(10)
    @images = get_images(@movies)
  end

  def show
    @movie = Movie.find(params[:id])
  end


  private

  def redirect_to_signin
    redirect_to new_user_session_path unless user_signed_in?
  end

  def get_images(movies)
    images = []
    movies.each do |m|
      images << m.movie_image
    end
    return images
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/friends/show.html.haml
自分の友達がオススメしている動画一覧

app/views/layouts/_header.html.haml
.header
  .header__content
    .header__content--title
      =link_to root_path, class: "header__content--title" do
        %h1 MOVIE HOLIC
    - if user_signed_in?
      .header__content--user
        = current_user.name
      .header__content--menu
        = react_component("Menu") 

app/views/layouts/_notifications.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width,initial-scale=1.0"}/
    %title MovieHolic
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    -# <!-- application.html.erb in Head tag below turbolinks -->
    = javascript_pack_tag 'application'

  %body
    = render partial: 'layouts/header'
    .contents
      = render partial: 'layouts/notifications'
      = yield

app/views/movies/index.html.haml
.top-contents
  = react_component("TopImage", {images: @images})

.low-contents
  .low-contents__elements
    %h1.low-contents__elements--caption Let's choose movie!
    .low-contents__elements--movies
      - @movies.each do |m|
        = react_component("Movie", {id: m.id, title: m.title, summary: m.summary, image: m.movie_image})

- if current_user.try(:admin?)
  = link_to '管理者専用ページ', rails_admin_path, style: "color: white"

app/views/movies/show.html.haml
.show-wrapper
  .show-top
    = react_component("Player", {id: @movie.id, title: @movie.title, video: @movie.movie_url, sumarry: @movie.summary})